name: Publish Image
# author: Michelangelo Serpico
description: Gemini Certificate image publishing workflow
# branding:  
#   icon: align-left
#   color: blue

on:
  push:
    tags: ["v*"]

env:
  REGISTRY: ghcr.io
  IMAGE_ID: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push
        run: |
          docker build . -t $IMAGE_ID
          docker push $IMAGE_ID
        # tags: |
        #   $IMAGE_ID:latest
        #   $IMAGE_ID:${{ github.run_number }}
